name: Build
on: [push]
jobs:
  build:
    name: Ubuntu->Windows Cross Compile
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install deps
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu kinetic universe"
        sudo apt update
        sudo apt install g++-mingw-w64-x86-64
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
        x86_64-w64-mingw32-g++ -v
    - name: Build
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: wrun
        path: wrun.exe
